name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      [
        ".github/workflows/storybook.yml",
        "lib/stories/**",
        "lib/**/*",
        "package-lock.json",
      ]

jobs:
  lint-and-test:
    uses: ./.github/workflows/shared-steps.yml
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci
      - run: npm run build:storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static # The folder that the build:storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: .nojekyll
  build-and-deploy-cdn:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci

      - name: Build CDN component
        run: npm run build:cdn

      - name: Deploy CDN
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-cdn
          clean: true
          branch: master
